Weather/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Weather/Models/PaginationViewModel.cs
using Weather.DAL.Models;

namespace Weather.Models
{
    /// <summary>
    /// Модель представления для пагинации погодных записей.
    /// </summary>
    public class PaginationViewModel
    {
        /// <summary>
        /// Список погодных записей на текущей странице.
        /// </summary>
        public List<WeatherRecord> Records { get; set; }

        /// <summary>
        /// Год, по которому производится фильтрация.
        /// </summary>
        public int Year { get; set; }

        /// <summary>
        /// Месяц, по которому производится фильтрация.
        /// </summary>
        public int Month { get; set; }

        /// <summary>
        /// Номер текущей страницы.
        /// </summary>
        public int Page { get; set; }

        /// <summary>
        /// Общее количество страниц.
        /// </summary>
        public int TotalPages { get; set; }

        /// <summary>
        /// Показывает, есть ли предыдущая страница.
        /// </summary>
        public bool HasPreviousPage
        {
            get { return Page > 1; }
        }

        /// <summary>
        /// Показывает, есть ли следующая страница.
        /// </summary>
        public bool HasNextPage
        {
            get { return Page < TotalPages; }
        }
    }


}

Weather/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using Weather.BLL.Interfaces;
using Weather.DAL.Models;
using Weather.Models;

namespace Weather.Controllers
{
    /// <summary>
    /// Контроллер для управления погодными данными.
    /// </summary>
    public class WeatherController : Controller
    {
        private readonly IWeatherService _weatherService;

        /// <summary>
        /// Инициализирует новый экземпляр контроллера WeatherController.
        /// </summary>
        /// <param name="weatherService">Сервис для работы с погодными данными.</param>
        public WeatherController(IWeatherService weatherService)
        {
            _weatherService = weatherService;
        }

        /// <summary>
        /// Главная страница.
        /// </summary>
        /// <returns>Представление главной страницы.</returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Страница загрузки архивов погодных условий.
        /// </summary>
        /// <returns>Представление страницы загрузки.</returns>
        public IActionResult Upload()
        {
            return View();
        }

        /// <summary>
        /// Действие для обработки загрузки файлов Excel.
        /// </summary>
        /// <param name="files">Список файлов для загрузки.</param>
        /// <returns>Редирект на главную страницу.</returns>
        [HttpPost]
        public async Task<IActionResult> Upload(List<IFormFile> files)
        {
            if (files != null && files.Count > 0)
            {
                List<Stream> fileStreams = new List<Stream>();

                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        var stream = file.OpenReadStream();
                        fileStreams.Add(stream);
                    }
                }

                // Вызываем сервис для обработки загруженных файлов Excel
                bool result = await _weatherService.UploadWeatherData(fileStreams);
                if (!result)
                {
                    // Обработка ошибок загрузки
                    ModelState.AddModelError("", "Ошибка загрузки файла.");
                }
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Страница просмотра архивов погодных условий.
        /// </summary>
        /// <returns>Представление страницы просмотра погодных данных.</returns>
        public IActionResult ViewWeather()
        {
            return View();
        }

        /// <summary>
        /// Действие для фильтрации записей о погоде по месяцам и годам.
        /// </summary>
        /// <param name="year">Год для фильтрации.</param>
        /// <param name="month">Месяц для фильтрации.</param>
        /// <param name="page">Номер страницы.</param>
        /// <returns>Представление страницы просмотра погодных данных с примененными фильтрами.</returns>
        public async Task<IActionResult> FilterWeatherData(int year, int month, int page = 1)
        {
            var pageSize = 10; // Количество записей на странице

            var (filteredRecords, totalRecordsCount) = await _weatherService.FilterWeatherDataByYearAndMonth(year, month, page, pageSize);
            var totalPages = (int)Math.Ceiling((double)totalRecordsCount / pageSize); // Вычисляем общее количество страниц


            var viewModel = new PaginationViewModel
            {
                Records = filteredRecords,
                Year = year,
                Month = month,
                Page = page,
                TotalPages = totalPages
            };

            return View("ViewWeather", viewModel);
        }

    }
}

Weather/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Weather/Views/Weather/Index.cshtml
@{
    ViewData["Title"] = "Главная страница";
}

<h1>Главная страница</h1>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>Меню</h2>
            <ul>
                <li><a asp-controller="Weather" asp-action="ViewWeather">Просмотр архивов погодных условий</a></li>
                <li><a asp-controller="Weather" asp-action="Upload">Загрузка архивов погодных условий</a></li>
            </ul>
        </div>
        <div class="col-md-6">
            <!-- Здесь можно разместить другое содержимое главной страницы -->
        </div>
    </div>
</div>

Weather/Views/Weather/Upload.cshtml
@{
    ViewData["Title"] = "Загрузка архивов погодных условий";
}

<h1>Загрузка архивов погодных условий</h1>

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="files">Выберите файлы Excel:</label>
        <input type="file" name="files" id="files" multiple required />
    </div>
    <button type="submit" class="btn btn-primary">Загрузить</button>
</form>

Weather/Views/Weather/ViewWeather.cshtml
@using System.Globalization
@using Weather.Models;
@model PaginationViewModel

<h2>Просмотр архивов погодных условий</h2>

<form method="post" action="@Url.Action("FilterWeatherData", "Weather")">
    <label for="year">Год:</label>
    <select id="year" name="year">
        @for (int i = DateTime.Now.Year; i >= 2000; i--)
        {
            <option value="@i">@i</option>
        }
    </select>

    <label for="month">Месяц:</label>
    <select id="month" name="month">
        @for (int i = 1; i <= 12; i++)
        {
            <option value="@i">@CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(i)</option>
        }
    </select>


    <button type="submit">Фильтровать</button>
</form>

@if (Model != null && Model!.Records != null && Model!.Records.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Дата</th>
                <th>Время</th>
                <th>Температура (°C)</th>
                <th>Относительная влажность (%)</th>
                <th>Точка росы (°C)</th>
                <th>Атмосферное давление (мм рт. ст.)</th>
                <th>Направление ветра</th>
                <th>Скорость ветра (м/с)</th>
                <th>Облачность (%)</th>
                <th>Нижняя граница облачности (м)</th>
                <th>Горизонтальная видимость (км)</th>
                <th>Погодные явления</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var record in Model.Records)
            {
                <tr>
                    <td>@(record.Date.HasValue ? record.Date.Value.ToShortDateString() : string.Empty)</td>
                    <td>@record.Time</td>
                    <td>@record.Temperature</td>
                    <td>@record.RelativeHumidity</td>
                    <td>@record.DewPoint</td>
                    <td>@record.AtmosphericPressure</td>
                    <td>@record.WindDirection</td>
                    <td>@record.WindSpeed</td>
                    <td>@record.Cloudiness</td>
                    <td>@(record.CloudBaseHeight)</td>
                    <td>@record.Visibility</td>
                    <td>@record.WeatherPhenomena</td>
                </tr>
            }
        </tbody>
    </table>

    <div class="pagination">
        @if (Model.Page > 1)
        {
            <a href="@Url.Action("FilterWeatherData", "Weather", new { year = Model.Year, month = Model.Month, page = Model.Page - 1 })" class="btn btn-primary">Предыдущая</a>
        }

        @if (Model.Page < Model.TotalPages)
        {
            <span> </span>
            <a href="@Url.Action("FilterWeatherData", "Weather", new { year = Model.Year, month = Model.Month, page = Model.Page + 1 })" class="btn btn-primary">Следующая</a>
        }
    </div>




}